# Generated by Django 2.2 on 2021-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0002_auto_20210308_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
