# Generated by Django 2.2.20 on 2021-04-23 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0003_message_is_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='start_time',
        ),
        migrations.AddField(
            model_name='individual',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(help_text='The Telegram ID of the chat', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.IntegerField(help_text='The Telegram ID of the chat', primary_key=True, serialize=False),
        ),
    ]
