# Generated by Django 2.2.20 on 2021-04-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0005_auto_20210423_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Individual',
            new_name='IndividualChat',
        ),
    ]
