# Generated by Django 2.2.20 on 2021-04-24 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0006_auto_20210423_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='schedule_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='schedule_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
