# Generated by Django 2.2.20 on 2021-04-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0007_auto_20210424_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(help_text='How many days after a group start date to send this message')),
                ('message', models.TextField()),
                ('comment', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='mpact.GroupChat')),
            ],
        ),
    ]
