# Generated by Django 2.2.20 on 2021-04-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0009_auto_20210428_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
