# Generated by Django 2.2.20 on 2021-05-07 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0010_scheduledmessage_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.IntegerField(help_text='The Telegram ID of the individual', primary_key=True, serialize=False)),
                ('username', models.TextField(null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(null=True)),
                ('study_id', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
