# Generated by Django 2.2.20 on 2021-05-07 12:10

from django.db import migrations

def populate_individuals(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    IndividualChat = apps.get_model('mpact', 'IndividualChat')
    Individual = apps.get_model('mpact', 'Individual')

    for chat in IndividualChat.objects.all():
        Individual.objects.create(
            id=chat.id,
            username=chat.username,
            first_name=chat.first_name,
            last_name=chat.last_name,
            study_id=chat.study_id,
            age=chat.age,
            gender=chat.gender,
            address=chat.address,
            notes=chat.notes,
        )
        print(f'created {chat}')


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0011_individual'),
    ]

    operations = [
        migrations.RunPython(populate_individuals),
    ]
